<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="Content-Style-Type" content="text/css">
<title></title>
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="824.48">
<style type="text/css">
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica}
p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px}
p.p3 {margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px Helvetica}
p.p4 {margin: 0.0px 0.0px 0.0px 0.0px; font: 9.0px Monaco}
p.p5 {margin: 0.0px 0.0px 0.0px 0.0px; font: 9.0px Monaco; color: #bf0000}
p.p6 {margin: 0.0px 0.0px 0.0px 0.0px; font: 9.0px Monaco; min-height: 12.0px}
p.p7 {margin: 0.0px 0.0px 0.0px 0.0px; font: 9.0px Monaco; color: #0000bf}
p.p8 {margin: 0.0px 0.0px 0.0px 0.0px; font: 9.0px Monaco; color: #007300}
p.p9 {margin: 0.0px 0.0px 0.0px 0.0px; font: 9.0px Monaco; color: #606060}
span.s1 {font: 18.0px Helvetica}
span.s2 {color: #0000bf}
span.s3 {color: #0000bf}
span.s4 {color: #0000bf}
span.s5 {color: #606060}
span.s6 {color: #007300}
span.s7 {color: #000000}
span.Apple-tab-span {white-space:pre}
</style>
</head>
<body>
<p class="p1"><span class="s1"><b>Exception<span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span></b></span><b>root error class</b></p>
<p class="p2"><br></p>
<p class="p1"><b>Inherits from: </b><a href="Object.html"><span class="s2"><b>Object</b></span></a></p>
<p class="p2"><br></p>
<p class="p1">The root of SuperCollider's error handling mechanism.</p>
<p class="p2"><br></p>
<p class="p1">Exception is an abstract class, defining basic error behavior. This class is not directly used in SuperCollider. Users may create subclasses of Exception to identify specific types of failure conditions.</p>
<p class="p2"><br></p>
<p class="p1">The built-in exception types are actually subclasses of <a href="Error.html"><span class="s3">Error</span></a> -- see its help file for the hierarchy.</p>
<p class="p2"><br></p>
<p class="p3"><b>Background: General exception handling</b></p>
<p class="p2"><br></p>
<p class="p1">An exception is any event that disrupts the normal execution flow of a program. In practice there is not much distinction between an exception and an error; in SuperCollider, we tend to speak of errors where other object-oriented languages (Java, C++) would use exception consistently.</p>
<p class="p2"><br></p>
<p class="p1">If a piece of code runs into an unexpected condition, it creates an exception object that holds information about the faulty condition, and then "throws" that object. From there, the interpreter unwinds backward through all the preceding stack frames looking for an exception handler that will "catch" the exception. The exception handler can take an alternate route to resolve the failure and continue normally; if this is not possible, it can re-throw the exception back to the previous stack frame. An exception that never gets caught causes execution to abort. In SuperCollider, this results in the standard error dump (see the <a href="../Language/Understanding-Errors.html"><span class="s3">Understanding-Errors</span></a> help file for details); in C++ or Java, the effect is catastrophic, causing the whole program to crash.</p>
<p class="p2"><br></p>
<p class="p1">Common syntax in other languages for exception handling is:</p>
<p class="p2"><br></p>
<p class="p4">try { ...code... }</p>
<p class="p4">catch { ...exception handler... }</p>
<p class="p2"><br></p>
<p class="p1">Specific languages may have other variants. The SuperCollider compiler doesn't have room for the "catch" keyword, so the syntax is simpler:</p>
<p class="p2"><br></p>
<p class="p4">try { ...code... } { ...exception handler... };</p>
<p class="p2"><br></p>
<p class="p1">With "try," if the error cannot be handled, you have to re-throw the error explicitly:</p>
<p class="p2"><br></p>
<p class="p4">try { ...code... } { <span class="s4">|error|</span></p>
<p class="p4"><span class="Apple-tab-span">	</span>if( test: can <span class="s4">I</span> handle the error? ) {</p>
<p class="p4"><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span>handle gracefully</p>
<p class="p4"><span class="Apple-tab-span">	</span>} { error.throw }</p>
<p class="p4">};</p>
<p class="p2"><br></p>
<p class="p1">SuperCollider includes a variant, borrowed from Scheme, in which the exception is always fatal, but the preceding code might have allocated some resources that need to be released before reporting the error. For example, you might open a file and do some processing on it that might encounter an error. Good practice is to close the file before the error halt, which you can do this way:</p>
<p class="p2"><br></p>
<p class="p4">file = <span class="s4">File</span>(path, <span class="s5">"r"</span>);</p>
<p class="p4">protect {</p>
<p class="p4"><span class="Apple-tab-span">	</span>work with the file here, which might cause an error</p>
<p class="p4">} {</p>
<p class="p4"><span class="Apple-tab-span">	</span>file.close;</p>
<p class="p4">};</p>
<p class="p2"><br></p>
<p class="p1">With "protect," the second function will execute even if there is no error, and any error will be passed up the chain.</p>
<p class="p2"><br></p>
<p class="p1">In Java, you can catch specific classes of exception. You can simulate this usage with the following construction:</p>
<p class="p2"><br></p>
<p class="p5">// Java-style</p>
<p class="p6"><br></p>
<p class="p4">try {<span class="Apple-converted-space">  </span>}</p>
<p class="p4">catch { <span class="s4">FileNotFoundException</span> e } { console.printLine(<span class="s5">"File not found: "</span> + e.path) }</p>
<p class="p4">catch { <span class="s4">EmptyFileException</span> e } { console.printLine(<span class="s5">"File is empty: "</span> + e.path) };</p>
<p class="p6"><br></p>
<p class="p5">// SuperCollider-style (hypothetical; these specific exceptions do not exist in the main library</p>
<p class="p6"><br></p>
<p class="p4">try {<span class="Apple-converted-space">  </span>} { <span class="s4">|error|</span></p>
<p class="p4"><span class="Apple-tab-span">	</span>switch(error.species.name)</p>
<p class="p4"><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span>{ <span class="s6">'FileNotFoundException'</span> } { postln(<span class="s5">"File not found:"</span> + e.path) }</p>
<p class="p4"><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span>{ <span class="s6">'EmptyFileException'</span> } { postln(<span class="s5">"File is empty:"</span> + e.path) }</p>
<p class="p5"><span class="s7"><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span></span>// default condition: unhandled exception, rethrow</p>
<p class="p4"><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span>{ error.throw }</p>
<p class="p4">}</p>
<p class="p2"><br></p>
<p class="p1">Following is an example that recovers from a failed attempt to write into an immutable array, by re-attempting the write on a copy of the array.</p>
<p class="p2"><br></p>
<p class="p4">(</p>
<p class="p7"><span class="s7">~inPlaceSub = { </span>|array, find, replace|</p>
<p class="p4"><span class="Apple-tab-span">	</span>array.do({ <span class="s4">|item, i|</span></p>
<p class="p4"><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span>if(item == find) { array[i] = replace };</p>
<p class="p4"><span class="Apple-tab-span">	</span>});</p>
<p class="p4">};</p>
<p class="p6"><br></p>
<p class="p7"><span class="s7">~trySub = { </span>|array, find, replace|</p>
<p class="p4"><span class="Apple-tab-span">	</span>try {</p>
<p class="p4"><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span>~inPlaceSub.(array, find, replace)</p>
<p class="p7"><span class="s7"><span class="Apple-tab-span">	</span>} { </span>|error|</p>
<p class="p4"><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span>switch(error.species.name)</p>
<p class="p8"><span class="s7"><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span>{ </span>'PrimitiveFailedError'<span class="s7"> } {</span></p>
<p class="p4"><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span>if(error.what.find(<span class="s5">"immutable"</span>).notNil) {</p>
<p class="p9"><span class="s7"><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span></span>"caught ImmutableError"<span class="s7">.postln;</span></p>
<p class="p4"><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span>~inPlaceSub.(array.copy, find, replace)</p>
<p class="p4"><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span>} { <span class="s5">"unknown primitive exception"</span>.postln; error.throw; }</p>
<p class="p4"><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span>}</p>
<p class="p5"><span class="s7"><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span></span>// default case: unhandled exception, should die so re-throw error</p>
<p class="p4"><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span><span class="Apple-tab-span">	</span>{ <span class="s5">"unknown exception"</span>.postln; error.throw; }</p>
<p class="p4"><span class="Apple-tab-span">	</span>};</p>
<p class="p4">};</p>
<p class="p4">)</p>
<p class="p6"><br></p>
<p class="p5">// pass in a mutable array, OK</p>
<p class="p4">~trySub.((0..9), 9, 19);</p>
<p class="p6"><br></p>
<p class="p5">// pass in a literal array, Immutable exception is caught and handled</p>
<p class="p4">~trySub.(#[0, 1, 2, 3, 4, 5], 5, 6);</p>
<p class="p6"><br></p>
<p class="p5">// pass in a nonsense value, other exception is re-thrown</p>
<p class="p4">~trySub.(10, 5, 6);</p>
<p class="p2"><br></p>
</body>
</html>
